Repository gqmv/aero, pull requests merged in 2021-04, with the labels that each got.

#6 Adicionado arquivo requirements.txt
  requirements.txt
Labels: documentation

#15 Código até agora feito refatorado
  game.py
  main.py
  objects.py
  objeto.py
  settings.py
Labels: enhancement

#19 Adicionada documentação
  main.py
  objects.py
  settings.py
Labels: bug, documentation, enhancement

#20 inclusão da mecânica de temperatura
  .idea/.gitignore
  .idea/.name
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/pythonProject5.iml
  assets/water.png
  main.py
  objects.py
  settings.py
Labels: enhancement

#21 Delete .idea directory
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/pythonProject5.iml
Labels: bug

#23 Optimização do PR #20
  main.py
  objects.py
  settings.py
Labels: documentation, enhancement

#30 Adicionado Score
  main.py
  settings.py
Labels: enhancement

#40 integração do novo layout
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/pythonProject5.iml
  .idea/vcs.xml
  main.py
  menu
  objects.py
Labels: design

#48 Remoção de arquivos duplicados
  menu
  menu.py
Labels: bug
